version: "4"

services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3308:3308"
    command: --port=3308
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql