version: "4"

services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - "3307:3307"
    command: --port=3307
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql